# Generated by Django 4.2.4 on 2023-08-22 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorific', models.CharField(blank=True, choices=[('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.')], max_length=10, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_affiliation', models.CharField(blank=True, choices=[('SAARC', 'SAARC'), ('Non-SAARC', 'Non-SAARC')], max_length=10, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('whatsapp_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('num_papers', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=2, null=True)),
                ('paper1_id', models.CharField(blank=True, max_length=50, null=True)),
                ('paper2_id', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('Student', 'I am a Student'), ('Faculty', 'I am a Faculty'), ('Others', 'I am affiliated with industry/research labs/others')], max_length=30, null=True)),
                ('num_accompanying_people', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=2, null=True)),
                ('is_ishmt_member', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('ishmt_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ishmt_id_file', models.FileField(blank=True, null=True, upload_to='ishmt_ids/')),
                ('forgot_pass_token', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
